# Projeto 1 - Ciência dos Dados

Nome: _____

Nome: _____

Atenção: Serão permitidos grupos de três pessoas, mas com uma rubrica mais exigente. Grupos deste tamanho precisarão fazer um questionário de avaliação de trabalho em equipe

___
Carregando algumas bibliotecas:

In [58]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

In [59]:
print('Esperamos trabalhar no diretório')
print(os.getcwd())

Esperamos trabalhar no diretório
C:\Users\tainapb\Downloads\teste

In [60]:
import re 


def cleanup(text):
    """
        Função de limpeza muito simples que troca alguns sinais básicos por espaços
    """
    #import string
    punctuation = '[",!-.:?;çã'']' # Note que os sinais [] são delimitadores de um conjunto.
#     punctuation = '[!-.:?;]'
    pattern = re.compile(punctuation)
    
    text_subbed = re.sub(pattern, '', text)
    return text_subbed

In [61]:
def limpa_prep(texto): 
    lista=['a','e','é','i','o','u','ou', 'ante', 'após', 'até', 'se','com', 'conta', 'de', 'desde', 'em', 'entre', 'para', 'per', 'perante', 'por', 
          'sem', 'sob', 'sobre', 'tras', 'na', 'no', 'as','os', 'que','dos','das', 'um', 'uma', 'umas', 'da', 'do', 'o', 'as', 'pra','nas', 'nos', 'ao', 'seu','sua', 'suas', 'seus', 'às']
    lista_frase=texto.split()
    result=[palavra for palavra in lista_frase if palavra.lower() not in lista ]
    retorno=' '.join(result)
    return retorno

Carregando a base de dados com as notícias classificadas manualmente:

In [62]:
filename = 'dados.xlsx'

In [63]:
train = pd.read_excel(filename, sheet_name = 'Treinamento')
train.head(5)

,Categoria,Titulo,PrimeiroParag,Data,Pagina,Target,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Comprar ou vender?,Magazine Luiza (MGLU3) e Via (VIIA3) são os qu...,"Na última sexta-feira (25), o Governo Federal ...",02/03/2022 - 18:37,37.0,2.0,NaN,139.0,NaN
1,Economia,"Inflação argentina atinge 3,9% em janeiro, mai...","O Índice de Preços ao Consumidor (CPI, na sigl...",15/02/2022 - 16:56,88.0,1.0,NaN,NaN,NaN
2,Agro Times,"Preços do açúcar devem cair este ano, pequeno ...",O preço do açúcar bruto deve terminar este ano...,08/02/2022 - 11:05,113.0,1.0,NaN,NaN,NaN
3,Mercados,Bolsas europeias afundam após ataque russo à U...,As Bolsas europeias sofreram fortes quedas nes...,24/02/2022 - 8:11,58.0,0.0,NaN,NaN,NaN
4,Mercados,"Ibovespa abre em queda, com mercado monitorand...",O Ibovespa (IBOV) abriu esta sexta-feira (4) e...,04/03/2022 - 10:11,28.0,1.0,NaN,NaN,NaN

In [64]:
test = pd.read_excel(filename, sheet_name = 'Teste')
test.head(5)

,Categoria,Titulo,PrimeiroParag,Data,Pagina,Target,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Agro Times,Importações de frango pela China devem aumenta...,As importações chinesas de carne de frango dev...,04/02/2022 - 10:00,123,2.0,NaN,125.0,NaN,NaN,NaN,NaN
1,Agro Times,Decreto presidencial aumenta número de adidos ...,O presidente Jair Bolsonaro editou decreto que...,14/02/2022 - 8:39,96,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,Economia,"Brasil terá déficit primário de 1,6% do PIB em...",A agência de classificação de risco Moody’s pr...,07/02/2022 - 11:29,117,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Empresas,Ações da Oi (OIBR3) afundam com três conselhei...,As ações da Oi afundam em um momento em que o ...,09/02/2022 - 13:38,107,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4,Economia,Brasil tem R$ 828 bi de investimentos contrata...,"O ministro da Economia, Paulo Guedes, afirmou ...",10/02/2022 - 18:47,102,2.0,NaN,NaN,NaN,NaN,NaN,NaN

___
## Classificador automático

Faça aqui uma descrição do seu assunto e o que considerou como relevante ou não relevante na classificação das notícias (Target).

Escolhemos o tema 'Economia' e classificamos como positivo(relevante(2)) o que afetava de forma positiva a economia do Brasil, como Negativo(irrelevante(1)) o que afetava de forma negativa a economia do Brasil e como neutro(0) o que não influenciava nessa.

___
### Montando um Classificador Naive-Bayes

Considerando apenas as mensagens da planilha Treinamento, ensine  seu classificador.

In [65]:
classe0=test.loc[test['Target']==0.0,:].PrimeiroParag.str.cat(sep=' ')
classe1=test.loc[test['Target']==1.0,:].PrimeiroParag.str.cat(sep=' ')
classe2=test.loc[test['Target']==2.0,:].PrimeiroParag.str.cat(sep=' ')

In [81]:
limpeza0 = limpa_prep(cleanup(classe0.lower()))
limpeza1 = limpa_prep(cleanup(classe1.lower()))
limpeza2 = limpa_prep(cleanup(classe2.lower()))

In [67]:
# Quebrando o texto em palavras
todas_palavras0 = limpeza0.split()

# Guardando as palavras como um pd.Series
serie_palavra0 = pd.Series(todas_palavras0)

tabela_palavra0 = serie_palavra0.value_counts()
tabela_palavra0

tabela_palavra0_relativa = serie_palavra0.value_counts(True)
tabela_palavra0_relativa

tabela_palavra0_relativa.sum()

tabela_palavra0_relativa["brasil"]

0.0008097165991902834

In [68]:
# Quebrando o texto em palavras
todas_palavras1 = limpeza1.split()

# Guardando as palavras como um pd.Series
serie_palavra1 = pd.Series(todas_palavras1)

tabela_palavra1 = serie_palavra1.value_counts()
tabela_palavra1

tabela_palavra1_relativa = serie_palavra1.value_counts(True)
tabela_palavra1_relativa.sum()

tabela_palavra1_relativa["brasil"]

0.007910823444804028

In [69]:
# Quebrando o texto em palavras
todas_palavras2= limpeza2.split()

# Guardando as palavras como um pd.Series
serie_palavra2 = pd.Series(todas_palavras2)

tabela_palavra2 = serie_palavra2.value_counts()
tabela_palavra2

tabela_palavra2_relativa = serie_palavra2.value_counts(True)
tabela_palavra2_relativa

tabela_palavra2_relativa.sum()

tabela_palavra2_relativa["brasil"]

0.007965482907401261

___
### Verificando a performance do Classificador

Agora você deve testar o seu classificador com a base de Testes.

In [70]:
junta_tudo=limpeza0 + limpeza1 + limpeza2

In [71]:
todas_palavras_junta_tudo=junta_tudo.split()
serie_junta_tudo=pd.Series(todas_palavras_junta_tudo)
serie_junta_tudo

0         presidente
1               jair
2          bolsonaro
3             editou
4            decreto
            ...
9492             mil
9493          pontos
9494         segundo
9495           dados
9496    preliminares
Length: 9497, dtype: object

In [72]:
#Probabilidade do todo
# frase=test.loc[test['PrimeiroParag']==1,:]
# frase
frase=test.PrimeiroParag.loc[2]
frase = cleanup(frase.lower())
frase.split()
test

,Categoria,Titulo,PrimeiroParag,Data,Pagina,Target,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Agro Times,Importações de frango pela China devem aumenta...,As importações chinesas de carne de frango dev...,04/02/2022 - 10:00,123,2.0,NaN,125.0,NaN,NaN,NaN,NaN
1,Agro Times,Decreto presidencial aumenta número de adidos ...,O presidente Jair Bolsonaro editou decreto que...,14/02/2022 - 8:39,96,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,Economia,"Brasil terá déficit primário de 1,6% do PIB em...",A agência de classificação de risco Moody’s pr...,07/02/2022 - 11:29,117,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Empresas,Ações da Oi (OIBR3) afundam com três conselhei...,As ações da Oi afundam em um momento em que o ...,09/02/2022 - 13:38,107,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4,Economia,Brasil tem R$ 828 bi de investimentos contrata...,"O ministro da Economia, Paulo Guedes, afirmou ...",10/02/2022 - 18:47,102,2.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
595,MT Labs,R$ 120 para investir em Petrobras (PETR4): sai...,"Na noite de quinta-feira (24), a Petrobras (PE...",25/02/2022 - 10:17,51,2.0,NaN,NaN,NaN,NaN,NaN,NaN
596,Mercados,"Ibovespa mostra resiliência e sobe 0,22%, mesm...",Operando entre baixas e altas praticamente a s...,14/02/2022 - 18:04,93,2.0,NaN,NaN,NaN,NaN,NaN,NaN
597,Empresas,Reservas da PetroReconcavo têm incremento de 5...,As reservas da PetroReconcavo (RECV3) tiveram ...,07/02/2022 - 21:10,115,1.0,NaN,NaN,NaN,NaN,NaN,NaN
598,Política,MP é contra estrada na Amazônia que não tem co...,O Ministério Público Federal no Acre se manife...,01/02/2022 - 14:36,135,1.0,NaN,NaN,NaN,NaN,NaN,NaN
599,Colunista Vitreo,Pré-Mercado: Que comecem os jogos — o primeiro...,Oportunidades do dia,01/02/2022 - 9:03,138,1.0,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
print(len(serie_palavra0))
prob0=len(serie_palavra0)/len(serie_junta_tudo)
print('A probabilidade de ser da target 0 é de {:.5f}'.format(prob0))
test.Target.value_counts(True)

3705
A probabilidade de ser da target 0 é de 0.39012

0.0    0.397985
2.0    0.314861
1.0    0.287154
Name: Target, dtype: float64

In [74]:
print(len(serie_palavra1))
prob1=len(serie_palavra1)/len(serie_junta_tudo)
print('A probabilidade de ser da target 1 é de {:.5f}'.format(prob1))
test.Target.value_counts(True)

2781
A probabilidade de ser da target 1 é de 0.29283

0.0    0.397985
2.0    0.314861
1.0    0.287154
Name: Target, dtype: float64

In [75]:
print(len(serie_palavra2))
prob2=len(serie_palavra2)/len(serie_junta_tudo)
print('A probabilidade de ser da target 2 é de {:.5f}'.format(prob2))
test.Target.value_counts(True)

3013
A probabilidade de ser da target 2 é de 0.31726

0.0    0.397985
2.0    0.314861
1.0    0.287154
Name: Target, dtype: float64

___
### Concluindo

In [76]:
#fazer as probabilidades relativas e a priori de acordo com as frases do test e saber a probabilidade de ser 1 ou 2. O mais provável é igu
palavras = frase.split()

# Guardando as palavras como um pd.Series
serie_frase = pd.Series(palavras)
serie_frase

tabela_frase_relativa = serie_frase.value_counts(True)
tabela_frase_relativa

probFraseDado0 = 1
probFraseDado1= 1
probFraseDado2= 1


totaldepalavras1 = tabela_palavra1.sum()
totaldepalavras2 = tabela_palavra2.sum()
totaldepalavras0 = tabela_palavra0.sum()

totaldepalavrasdiferentes =serie_junta_tudo.count()



valor1 =1
valor2 =1
valor0 =1
for palavra in palavras:
    if palavra in tabela_palavra1:
        valor = (tabela_palavra1[palavra] + 1)/(totaldepalavras1 + totaldepalavrasdiferentes)
        valor1*=valor
    if palavra in tabela_palavra2:
        valor = (tabela_palavra2[palavra] + 1)/(totaldepalavras2 + totaldepalavrasdiferentes)
        valor2*=valor
    if palavra in tabela_palavra0:
        valor = (tabela_palavra0[palavra] + 1)/(totaldepalavras0 + totaldepalavrasdiferentes)
        valor0*=valor

dicio = {"Valor1":valor1, "Valor2":valor2, "Valor0":valor0}
maior = 0
target = ""
for i in dicio:
    if dicio[i]>maior:
        maior = dicio[i]
        target = i
print(target)

Valor2

In [77]:
listafinal = []
for frase in test.PrimeiroParag:
    frase = str(frase)
    frase = cleanup(frase.lower())
    palavras = frase.split()
    totaldepalavras1 = tabela_palavra1.sum()
    totaldepalavras2 = tabela_palavra2.sum()
    totaldepalavras0 = tabela_palavra0.sum()

    totaldepalavrasdiferentes =serie_junta_tudo.value_counts().count()


    valor1 =1
    valor2 =1
    valor0 =1
    target=""
    for palavra in palavras:
        if palavra in tabela_palavra1:
            valor = (tabela_palavra1[palavra] + 1)/(totaldepalavras1 + totaldepalavrasdiferentes)
            valor1*=valor
        else:
            valor = (1)/(totaldepalavras1 + totaldepalavrasdiferentes)
            valor1*=valor
        if palavra in tabela_palavra2:
            valor = (tabela_palavra2[palavra] + 1)/(totaldepalavras2 + totaldepalavrasdiferentes)
            valor2*=valor
        else:
            valor = (1)/(totaldepalavras2 + totaldepalavrasdiferentes)
            valor2*=valor
        if palavra in tabela_palavra0:
            valor = (tabela_palavra0[palavra] + 1)/(totaldepalavras0 + totaldepalavrasdiferentes)
            valor0*=valor
        else:
            valor = (1)/(totaldepalavras0 + totaldepalavrasdiferentes)
            valor0*=valor
        
    lista = [valor1,valor2,valor0]
    maior = max(lista)
    if maior == valor1:
            listafinal.append("1")
    if maior == valor2:
            listafinal.append("2")
    if maior == valor0:
            listafinal.append("0")
listafinal

test['Target_Robo'] = listafinal

In [78]:
test

,Categoria,Titulo,PrimeiroParag,Data,Pagina,Target,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Target_Robo
0,Agro Times,Importações de frango pela China devem aumenta...,As importações chinesas de carne de frango dev...,04/02/2022 - 10:00,123,2.0,NaN,125.0,NaN,NaN,NaN,NaN,2
1,Agro Times,Decreto presidencial aumenta número de adidos ...,O presidente Jair Bolsonaro editou decreto que...,14/02/2022 - 8:39,96,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0
2,Economia,"Brasil terá déficit primário de 1,6% do PIB em...",A agência de classificação de risco Moody’s pr...,07/02/2022 - 11:29,117,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
3,Empresas,Ações da Oi (OIBR3) afundam com três conselhei...,As ações da Oi afundam em um momento em que o ...,09/02/2022 - 13:38,107,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4,Economia,Brasil tem R$ 828 bi de investimentos contrata...,"O ministro da Economia, Paulo Guedes, afirmou ...",10/02/2022 - 18:47,102,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,MT Labs,R$ 120 para investir em Petrobras (PETR4): sai...,"Na noite de quinta-feira (24), a Petrobras (PE...",25/02/2022 - 10:17,51,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2
596,Mercados,"Ibovespa mostra resiliência e sobe 0,22%, mesm...",Operando entre baixas e altas praticamente a s...,14/02/2022 - 18:04,93,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2
597,Empresas,Reservas da PetroReconcavo têm incremento de 5...,As reservas da PetroReconcavo (RECV3) tiveram ...,07/02/2022 - 21:10,115,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
598,Política,MP é contra estrada na Amazônia que não tem co...,O Ministério Público Federal no Acre se manife...,01/02/2022 - 14:36,135,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
599,Colunista Vitreo,Pré-Mercado: Que comecem os jogos — o primeiro...,Oportunidades do dia,01/02/2022 - 9:03,138,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1

In [79]:
pd.crosstab(test.Target, test.Target_Robo)

Target_Robo    0    1    2
Target
0.0          155    2    1
1.0            0  112    2
2.0            0    4  121

___
### Qualidade do Classificador a partir de novas separações das notícias entre Treinamento e Teste

Caso for fazer esse item do Projeto

In [80]:
amo meu marido arthur <3

SyntaxError: invalid syntax (<ipython-input-80-30a126875b93>, line 1)

___
## Aperfeiçoamento:

Trabalhos que conseguirem pelo menos conceito B vão evoluir em conceito dependendo da quantidade de itens avançados:

* IMPLEMENTOU outras limpezas e transformações que não afetem a qualidade da informação contida nas notícias. Ex: stemming, lemmatization, stopwords
* CONSIDEROU mais de duas caterogias na variável Target e INCREMENTOU a quantidade de notícias, mantendo pelo menos 250 notícias por caterogia (OBRIGATÓRIO PARA TRIOS, sem contar como item avançado)
* Para Target com duas categorias: CRIOU pelo menos quatro categorias intermediárias de relevância baseadas na probabilidade: ex.: muito relevante, relevante, neutro, irrelevante, muito irrelevante
* EXPLICOU porquê não pode usar o próprio classificador para gerar mais amostras de treinamento
* PROPÔS diferentes cenários para Naïve Bayes fora do contexto do projeto (pelo menos dois cenários, exceto aqueles já apresentados em sala pelos professores: por exemplo, filtro de spam)
* SUGERIU e EXPLICOU melhorias reais com indicações concretas de como implementar (indicar como fazer e indicar material de pesquisa)
* FEZ o item Qualidade do Classificador a partir de novas separações das Notícias entre Treinamento e Teste descrito no enunciado do projeto (OBRIGATÓRIO para conceitos A ou A+)

___
## Referências

[Naive Bayes and Text Classification](https://arxiv.org/pdf/1410.5329.pdf)  **Mais completo**

[A practical explanation of a Naive Bayes Classifier](https://monkeylearn.com/blog/practical-explanation-naive-bayes-classifier/) **Mais simples**